/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BaseRolloutStrategyAllOf } from './base-rollout-strategy-all-of';
import { BaseStrategy } from './base-strategy';
import { RolloutStrategyAttribute } from './rollout-strategy-attribute';

/**
 * @type BaseRolloutStrategy
 * @export
 */
export type BaseRolloutStrategy = BaseRolloutStrategyAllOf & BaseStrategy;



