/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FeatureRolloutStrategyAttribute } from './feature-rollout-strategy-attribute';

/**
 * 
 * @export
 * @interface FeatureRolloutStrategyAllOf
 */
export interface FeatureRolloutStrategyAllOf {
    /**
     * 
     * @type {Array<FeatureRolloutStrategyAttribute>}
     * @memberof FeatureRolloutStrategyAllOf
     */
    attributes: Array<FeatureRolloutStrategyAttribute>;
}


