/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BaseRolloutStrategy } from './base-rollout-strategy';
import { FeatureRolloutStrategyAllOf } from './feature-rollout-strategy-all-of';
import { FeatureRolloutStrategyAttribute } from './feature-rollout-strategy-attribute';

/**
 * @type FeatureRolloutStrategy
 * This is the model for the rollout strategy as required by Dacha and Edge
 * @export
 */
export type FeatureRolloutStrategy = BaseRolloutStrategy & FeatureRolloutStrategyAllOf;



