/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BaseRolloutStrategyAttribute } from './base-rollout-strategy-attribute';
import { RolloutStrategyAttributeConditional } from './rollout-strategy-attribute-conditional';
import { RolloutStrategyFieldType } from './rollout-strategy-field-type';

/**
 * @type FeatureRolloutStrategyAttribute
 * @export
 */
export type FeatureRolloutStrategyAttribute = BaseRolloutStrategyAttribute;



