/* tslint:disable */
/* eslint-disable */
/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RolloutStrategyAttributeConditional } from './rollout-strategy-attribute-conditional';
import { RolloutStrategyFieldType } from './rollout-strategy-field-type';

/**
 * 
 * @export
 * @interface RolloutStrategyAttribute
 */
export interface RolloutStrategyAttribute {
    /**
     * An ID that needs to exist for validation
     * @type {string}
     * @memberof RolloutStrategyAttribute
     */
    id?: string | null;
    /**
     * 
     * @type {RolloutStrategyAttributeConditional}
     * @memberof RolloutStrategyAttribute
     */
    conditional: RolloutStrategyAttributeConditional;
    /**
     * 
     * @type {string}
     * @memberof RolloutStrategyAttribute
     */
    fieldName: string;
    /**
     * the value(s) associated with this rule
     * @type {Array<any>}
     * @memberof RolloutStrategyAttribute
     */
    values?: Array<any>;
    /**
     * 
     * @type {RolloutStrategyFieldType}
     * @memberof RolloutStrategyAttribute
     */
    type: RolloutStrategyFieldType;
}


