# ================================
# STAGE 0: Setup Base Image
# ================================
FROM node:24-alpine AS base

RUN apk update && apk add --no-cache bash
RUN mkdir -p /pnpm
ENV PNPM_HOME=/pnpm
ENV PATH=$PATH:/pnpm:/pnpm/bin
# Install pnpm globally
RUN npm install -g pnpm@11 && mkdir -p /sdk

# Set working directory
WORKDIR /sdk

COPY / /sdk/

# Install all dependencies
RUN pnpm install --frozen-lockfile

RUN pnpm run build:packages
RUN pnpm run build:plugins
#RUN pnpm --filter './examples/todo-server-tests' run build
RUN pnpm --filter './examples/todo-backend-typescript' run build

