/* tslint:disable */

/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BaseUIStrategy
 */
export interface BaseUIStrategy {
  /**
   * names are unique in a case insensitive fashion
   * @type {string}
   * @memberof BaseUIStrategy
   */
  name?: string;
  /**
   * the colour used to display the strategy in the UI. indexed table of background/foreground combos.
   * @type {number}
   * @memberof BaseUIStrategy
   */
  colouring?: number | null;
  /**
   * Disable this strategy across all feature values that are using it
   * @type {boolean}
   * @memberof BaseUIStrategy
   */
  disabled?: boolean;
  /**
   * url to avatar (if any). Not sent to SDK. Preferably a unicorn.
   * @type {string}
   * @memberof BaseUIStrategy
   */
  avatar?: string | null;
}
