/* tslint:disable */

/**
 * FeatureServiceApi
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FeatureRolloutStrategyAttribute } from "./feature-rollout-strategy-attribute";

/**
 *
 * @export
 * @interface FeatureRolloutStrategyAllOf
 */
export interface FeatureRolloutStrategyAllOf {
  /**
   * strategy id
   * @type {string}
   * @memberof FeatureRolloutStrategyAllOf
   */
  id: string;
  /**
   *
   * @type {Array<FeatureRolloutStrategyAttribute>}
   * @memberof FeatureRolloutStrategyAllOf
   */
  attributes?: Array<FeatureRolloutStrategyAttribute>;
}
