name: Build featurehub-react-sdk

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
    - 'featurehub-react-sdk/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
        working-directory: featurehub-react-sdk
      - name: Install peer dependencies
        run: npm install featurehub-javascript-client-sdk react
        working-directory: featurehub-react-sdk
      - name: Build (tests build of commonjs and es6 modules)
        run: npm run build
        working-directory: featurehub-react-sdk
      - name: Lint
        run: npm run lint
        working-directory: featurehub-react-sdk
