name: Publish featurehub-solid-sdk package to NPM registry
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "22.20.0"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
        working-directory: featurehub-solid-sdk
      - name: Install peer dependencies
        run: npm install featurehub-javascript-client-sdk solid-js
        working-directory: featurehub-solid-sdk
      - name: Compile sources and Publish to NPM
        run: npm run release
        working-directory: featurehub-solid-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
