name: Publish featurehub-javascript-node-sdk package to NPM registry
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
        working-directory: featurehub-javascript-node-sdk
      - name: Ensure everything is linted correctly
        run: npm run lint
        working-directory: featurehub-javascript-node-sdk
      - name: Compile sources and Publish to NPM
        run: npm run release
        working-directory: featurehub-javascript-node-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
